name: league_of_api
description: A library to facilitate access to the Riot API. Provide easy access to endpoint and dto for an easy access to the response data.
version: 0.1.0
repository: https://github.com/Driky/LeagueOfApi
issue_tracker: https://github.com/Driky/LeagueOfApi/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  #fixme: remove once out beta
  dio: ^4.0.0-beta7
  equatable: ^2.0.0
  json_annotation: ^4.0.0
  #pretty_dio_logger: ^1.1.1

dev_dependencies:
  mockito: ^5.0.1
  pedantic: ^1.9.0
  test: ^1.14.4
  build_runner: ^1.12.1
  json_serializable: ^4.0.3
