name: league_of_api
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.9.3 <3.0.0'

dependencies:
  dio: ^3.0.10
  json_annotation: ^3.1.1
  pretty_dio_logger: ^1.1.1
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  test_coverage: ^0.4.2
  #build_runner: ^1.12.1
  #json_serializable: ^4.0.3
