enum Queue { RANKED_SOLO_5x5, RANKED_FLEX_SR, RANKED_FLEX_TT }
const Map<Queue, String> QUEUES = {
  Queue.RANKED_SOLO_5x5: 'RANKED_SOLO_5x5',
  Queue.RANKED_FLEX_SR: 'RANKED_FLEX_SR',
  Queue.RANKED_FLEX_TT: 'RANKED_FLEX_SR'
};
