name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:2.9.3

    steps:
      - uses: actions/checkout@v1
      - name: Install app dependencies
        run: pub get
      - name: Test app
        run: pub run test
      - name: Generate code coverage
        run: pub run test_coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: coverage/lcov.info